version: "3.9"
services:
  app:
    build: .
    container_name: "link_service"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: islam20011
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
volumes:
  postgres_data: